version: '2'

services:
  backend:
    build: backend
    env_file:
      - backend/docker.env
    links:
      - redis
      - pg
      - webapp

  webapp:
    build: webapp
    ports:
      - "443:443"
      - "80:80"

  pg:
    image: postgres:15.2-alpine
    env_file:
      - backend/docker.env
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine

volumes:
  pg_db: