version: '3'

services:
  cardhero-backend:
    image: "ghcr.io/rohitawate/cardhero-backend:latest"
    container_name: cardhero-backend
    env_file:
      - backend/docker.env
    depends_on:
      - cardhero-redis
      - cardhero-pg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080"]
      interval: 1m
      timeout: 10s
      retries: 3

  cardhero-webapp:
    image: "ghcr.io/rohitawate/cardhero-webapp:latest"
    container_name: cardhero-webapp
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - cardhero-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp"]
      interval: 1m
      timeout: 10s
      retries: 3

  cardhero-pg:
    image: postgres:15.2-alpine
    container_name: cardhero-pg
    env_file:
      - backend/docker.env
    ports:
      - "5588:5432"
    volumes:
      - cardhero-pg-vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "pg"]
      interval: 1m
      timeout: 10s
      retries: 3

  cardhero-redis:
    image: redis:7.0-alpine
    container_name: cardhero-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  cardhero-pg-vol:
