version: '3'

services:
  backend:
    image: "ghcr.io/rohitawate/cardhero-backend:latest"
    env_file:
      - backend/docker.env
    depends_on:
      - redis
      - pg
      - ml
    networks:
      - cardhero-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:8080" ]
      interval: 1m
      timeout: 10s
      retries: 3

  webapp:
    image: "ghcr.io/rohitawate/cardhero-webapp:latest"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    networks:
      - cardhero-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://webapp" ]
      interval: 1m
      timeout: 10s
      retries: 3

  ml:
    image: "ghcr.io/rohitawate/cardhero-ml:latest"
    networks:
      - cardhero-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://ml:8000" ]
      interval: 1m
      timeout: 10s
      retries: 3

  pg:
    image: postgres:15.2-alpine
    env_file:
      - backend/docker.env
    ports:
      - "5588:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data
    networks:
      - cardhero-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "pg" ]
      interval: 1m
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0-alpine
    networks:
      - cardhero-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  cardhero-net:

volumes:
  pg_db:
