name: Build Docker images and push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, webapp]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        cd ${{ matrix.component }}
        docker build -t cardhero-${{matrix.component}}-${{ steps.git_hash.outputs.git_hash }} .
        docker tag cardhero-${{matrix.component}}-${{ steps.git_hash.outputs.git_hash }} cardhero-${{matrix.component}}:latest
      
    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image to GHCR
      run: |
        docker push ghcr.io/rohitawate/cardhero-${{matrix.component}}:latest
