name: Build Docker images and push to GHCR

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, webapp]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        cd ${{ matrix.component }}
        docker build -t ghcr.io/rohitawate/cardhero-${{matrix.component}}:latest .
      
    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image to GHCR
      run: |
        docker push ghcr.io/rohitawate/cardhero-${{matrix.component}}:latest
